-- =================================================================
--  AI-ADVISOR DATABASE SCHEMA
--  Version 1.0
--  Run this script in your Supabase SQL Editor to set up the entire database.
-- =================================================================

-- ========= TABLES =========

-- Stores unstructured journal entries from the user.
CREATE TABLE IF NOT EXISTS journal_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stores comments from AI agents on specific journal entries.
CREATE TABLE IF NOT EXISTS journal_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entry_id UUID REFERENCES journal_entries(id) ON DELETE CASCADE NOT NULL,
    agent_name VARCHAR(50) NOT NULL,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stores user profile information, including gamification elements.
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    username VARCHAR(50) UNIQUE,
    level INT DEFAULT 1,
    xp_points INT DEFAULT 0,
    xp_to_next_level INT DEFAULT 100,
    updated_at TIMESTAMPTZ DEFAULT NOW() -- Set default value here
);

-- Logs every user message and AI response for conversation history.
CREATE TABLE IF NOT EXISTS ai_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    agent_name VARCHAR(50) NOT NULL,
    user_message TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stores the daily synthesis generated by the Master Overseer AI.
CREATE TABLE IF NOT EXISTS daily_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    summary_text TEXT NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, date)
);

-- Stores memory summaries and token counts for each user/agent pair.
CREATE TABLE IF NOT EXISTS memory_stats (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    agent_name VARCHAR(50) NOT NULL,
    cumulative_summary TEXT,
    summarized_until_timestamp TIMESTAMPTZ,
    active_token_count INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMPTZ DEFAULT NOW(), -- Set default value here
    PRIMARY KEY (user_id, agent_name)
);


-- ========= INDEXES (for performance) =========

CREATE INDEX IF NOT EXISTS idx_journal_entries_user_id ON journal_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_journal_comments_entry_id ON journal_comments(entry_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_user_id_agent_name ON ai_interactions(user_id, agent_name);


-- ========= ROW LEVEL SECURITY (RLS) =========

-- --- Enable RLS on all tables ---
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_stats ENABLE ROW LEVEL SECURITY;

-- --- Create Policies ---
-- Drop policies if they exist to ensure a clean run
DROP POLICY IF EXISTS "Allow individual access to own journal entries" ON journal_entries;
CREATE POLICY "Allow individual access to own journal entries" ON journal_entries FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual read access to comments on own journal entries" ON journal_comments;
CREATE POLICY "Allow individual read access to comments on own journal entries" ON journal_comments FOR SELECT USING (EXISTS (SELECT 1 FROM journal_entries WHERE journal_entries.id = journal_comments.entry_id AND journal_entries.user_id = auth.uid()));

DROP POLICY IF EXISTS "Allow individual access to own user profile" ON user_profiles;
CREATE POLICY "Allow individual access to own user profile" ON user_profiles FOR ALL USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow individual access to own AI interactions" ON ai_interactions;
CREATE POLICY "Allow individual access to own AI interactions" ON ai_interactions FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual access to own daily summaries" ON daily_summaries;
CREATE POLICY "Allow individual access to own daily summaries" ON daily_summaries FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual read access to own memory stats" ON memory_stats;
CREATE POLICY "Allow individual read access to own memory stats" ON memory_stats FOR SELECT USING (auth.uid() = user_id);