-- =================================================================
--  CLARITY AI (AI-ADVISOR) DATABASE SCHEMA
--  Version 2.0
--  Run this script in your Supabase SQL Editor to set up the entire database.
-- =================================================================

-- ========= TABLES =========

-- 1. Stores unstructured journal entries from the user.
CREATE TABLE IF NOT EXISTS journal_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Stores comments from AI agents on specific journal entries.
CREATE TABLE IF NOT EXISTS journal_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entry_id UUID REFERENCES journal_entries(id) ON DELETE CASCADE NOT NULL,
    agent_name VARCHAR(50) NOT NULL,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Stores user profile information, including gamification elements.
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    username VARCHAR(50) UNIQUE,
    level INT DEFAULT 1,
    xp_points INT DEFAULT 0,
    xp_to_next_level INT DEFAULT 100,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Logs every user message and AI response for conversation history.
CREATE TABLE IF NOT EXISTS ai_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    agent_name VARCHAR(50) NOT NULL,
    user_message TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Stores the daily synthesis generated by the Master Overseer AI.
CREATE TABLE IF NOT EXISTS daily_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    summary_text TEXT NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, date)
);

-- 6. Stores memory summaries and token counts for each user/agent pair.
CREATE TABLE IF NOT EXISTS memory_stats (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    agent_name VARCHAR(50) NOT NULL,
    cumulative_summary TEXT,
    summarized_until_timestamp TIMESTAMPTZ,
    active_token_count INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, agent_name)
);

-- 7. Stores body weight logs over time.
CREATE TABLE IF NOT EXISTS weight_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    weight_kg NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Stores water consumption logs.
CREATE TABLE IF NOT EXISTS water_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    amount_ml INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Stores detailed food & nutrition logs.
CREATE TABLE IF NOT EXISTS food_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    food_name TEXT NOT NULL,
    meal_type VARCHAR(50) NOT NULL,
    serving_size TEXT,
    calories NUMERIC NOT NULL DEFAULT 0,
    macros JSONB DEFAULT '{}'::jsonb,
    micros JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Stores user daily tracker goals.
CREATE TABLE IF NOT EXISTS user_goals (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    daily_water_goal_ml INT,
    daily_calorie_goal INT,
    weight_goal_kg NUMERIC,
    weight_goal_type VARCHAR(50),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- ========= INDEXES (for query performance) =========

CREATE INDEX IF NOT EXISTS idx_journal_entries_user_id ON journal_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_journal_comments_entry_id ON journal_comments(entry_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_user_id_agent ON ai_interactions(user_id, agent_name);
CREATE INDEX IF NOT EXISTS idx_weight_logs_user_created ON weight_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_water_logs_user_created ON water_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_food_logs_user_created ON food_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_food_logs_meal_type ON food_logs(user_id, meal_type, created_at DESC);


-- ========= ROW LEVEL SECURITY (RLS) =========

-- Enable RLS on all tables
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE weight_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE water_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_goals ENABLE ROW LEVEL SECURITY;

-- Clean and recreate policies
DROP POLICY IF EXISTS "Allow individual access to own journal entries" ON journal_entries;
CREATE POLICY "Allow individual access to own journal entries" ON journal_entries FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual read access to comments on own journal entries" ON journal_comments;
DROP POLICY IF EXISTS "Allow individual access to comments on own journal entries" ON journal_comments;
CREATE POLICY "Allow individual access to comments on own journal entries" ON journal_comments FOR ALL USING (
    EXISTS (SELECT 1 FROM journal_entries WHERE journal_entries.id = journal_comments.entry_id AND journal_entries.user_id = auth.uid())
);

DROP POLICY IF EXISTS "Allow individual access to own user profile" ON user_profiles;
CREATE POLICY "Allow individual access to own user profile" ON user_profiles FOR ALL USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow individual access to own AI interactions" ON ai_interactions;
CREATE POLICY "Allow individual access to own AI interactions" ON ai_interactions FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual access to own daily summaries" ON daily_summaries;
CREATE POLICY "Allow individual access to own daily summaries" ON daily_summaries FOR ALL USING (auth.uid() = user_id);

-- Fixed: memory_stats requires FOR ALL to allow inserts and upserts from backend
DROP POLICY IF EXISTS "Allow individual read access to own memory stats" ON memory_stats;
DROP POLICY IF EXISTS "Allow individual access to own memory stats" ON memory_stats;
CREATE POLICY "Allow individual access to own memory stats" ON memory_stats FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual access to own weight logs" ON weight_logs;
CREATE POLICY "Allow individual access to own weight logs" ON weight_logs FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual access to own water logs" ON water_logs;
CREATE POLICY "Allow individual access to own water logs" ON water_logs FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual access to own food logs" ON food_logs;
CREATE POLICY "Allow individual access to own food logs" ON food_logs FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow individual access to own user goals" ON user_goals;
CREATE POLICY "Allow individual access to own user goals" ON user_goals FOR ALL USING (auth.uid() = user_id);


-- ========= STORED PROCEDURES / RPCs =========

-- 1. Aggregates today's tracker status for dashboard
CREATE OR REPLACE FUNCTION get_dashboard_data(user_uuid UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    start_of_day TIMESTAMPTZ := date_trunc('day', NOW() AT TIME ZONE 'UTC');
    v_water_intake INT := 0;
    v_calorie_intake NUMERIC := 0;
    v_latest_weight JSONB := NULL;
BEGIN
    SELECT COALESCE(SUM(amount_ml), 0)
    INTO v_water_intake
    FROM water_logs
    WHERE user_id = user_uuid AND created_at >= start_of_day;

    SELECT COALESCE(SUM(calories), 0)
    INTO v_calorie_intake
    FROM food_logs
    WHERE user_id = user_uuid AND created_at >= start_of_day;

    SELECT to_jsonb(w)
    INTO v_latest_weight
    FROM (
        SELECT id, user_id, weight_kg, created_at
        FROM weight_logs
        WHERE user_id = user_uuid
        ORDER BY created_at DESC
        LIMIT 1
    ) w;

    RETURN jsonb_build_object(
        'todays_water_intake', v_water_intake,
        'todays_calorie_intake', v_calorie_intake,
        'latest_weight_log', v_latest_weight
    );
END;
$$;

-- 2. Calculates today's nutrient breakdown
CREATE OR REPLACE FUNCTION get_daily_nutrient_breakdown(user_uuid UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    start_of_day TIMESTAMPTZ := date_trunc('day', NOW() AT TIME ZONE 'UTC');
    v_total_calories NUMERIC := 0;
    v_macros JSONB := '{}'::jsonb;
    v_micros JSONB := '{}'::jsonb;
BEGIN
    SELECT COALESCE(SUM(calories), 0)
    INTO v_total_calories
    FROM food_logs
    WHERE user_id = user_uuid AND created_at >= start_of_day;

    RETURN jsonb_build_object(
        'total_calories', v_total_calories,
        'macros', v_macros,
        'micros', v_micros
    );
END;
$$;

-- 3. Provides aggregated weight history for chart visualization
CREATE OR REPLACE FUNCTION get_weight_history_for_chart(user_uuid UUID, days_ago INT DEFAULT 7)
RETURNS TABLE (
    log_date TIMESTAMPTZ,
    avg_weight NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        date_trunc('day', created_at) AS log_date,
        ROUND(AVG(weight_kg)::numeric, 2) AS avg_weight
    FROM weight_logs
    WHERE user_id = user_uuid 
      AND created_at >= (NOW() AT TIME ZONE 'UTC' - (days_ago || ' days')::interval)
    GROUP BY date_trunc('day', created_at)
    ORDER BY log_date ASC;
END;
$$;